sudo: required
services:
  - docker

before_install:
  - docker build -t smermont/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t smermont/multi-client ./client
  - docker build -t smermont/multi-nginx ./nginx
  - docker build -t smermont/multi-server ./server
  - docker build -t smermont/multi-worker ./worker
  # Log in to the docker CLI.
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub.
  - docker push sergiomermont/multi-client
  - docker push sergiomermont/multi-nginx
  - docker push sergiomermont/multi-server
  - docker push sergiomermont/multi-worker